### ISSUE TITLE
note about .gitignore

### ISSUE THREAD

**Issue by bjoernklose** [Strider-CD/strider-ssh-deploy#17]
Hey guys!

Thanks for this great addition to strider.

One thing I just learned the hard way, which would be a good addition to the README

When preparing the `package.tar.gz` file, this extension respects all settings in a projects' `.gitignore` file.

So in case you are doing your build steps on the Strider server and want to deploy the final build results using this, make sure that your build destination folder is NOT listed in the `.gitignore` file (even though that might make sense for the rest of your dev workflow).

Suggestion: Would it be possible / useful to add a setting for following / ignoring the .gitignore files in a project directory?

**Comment by teone** [comment]
In the meanwhile I'm using this _dirty_ workaround to build and deploy a js application with the `custom scripts` and `SSH Deploy` plugins:

* _Prepare_ section: `npm install && bower install`
* _Deploy_ section: `grunt build`and `rm .gitignore` (and test and everything you need)
* _SSH Deploy_ plugin: with `transfer bundle` flag enable and post script `cp $HOME/[bundle_name]/dist/* /path/to/virtual/host/folder`

This maybe not the cleaner way to achieve this behavior but it is definitely working... Hope that can save someone from an headache...

**Comment by knownasilya** [comment]
Thanks @teone
