### ISSUE TITLE
No "delete server" button

### ISSUE THREAD

**Issue by bdest** [Strider-CD/strider-ssh-deploy#18]
Hi

I've made a typo in the "hosts" section, and there is no way (from the web) to delete the server.
I guess is possible to delete it from mongodb

**Comment by keyvanfatehi** [comment]
@bdest it's actually there, to the left of the name, it just got messed up (turned transparent or white) due to css. will fix in a PR shortly but just wanted to let you know

**Comment by reiven** [comment]
Thanks @keyvanfatehi !
