### ISSUE TITLE
Use git archive to make generic tarball

### ISSUE THREAD

**Issue by kfatehi** [Strider-CD/strider-ssh-deploy#2]
http://git-scm.com/docs/git-archive

**Comment by oliversalzburg** [comment]
@kfatehi What tests did you write for this? Is there any pre-existing code?

**Comment by oliversalzburg** [comment]
Relevant: #42 
And the current approach doesn't work with the Docker runner. I'll attempt an alternative solution

**Comment by kfatehi** [comment]
I think I was referring to the bundling tests here
https://github.com/Strider-CD/strider-ssh-deploy/blob/master/test/bundler_test.js
