### ISSUE TITLE
Please update the version on npm to 1.0.0

### ISSUE THREAD

**Issue by mastertinner** [Strider-CD/strider-ssh-deploy#34]

**Comment by knownasilya** [comment]
Plugins aren't installed fro npm. We have an ecosystem index which contains the released plugins.

**Comment by mastertinner** [comment]
Yes, but the initial installation of the plugin is done via npm during `npm install`. That's why every time I install Strider somewhere, I have to manually update all the plugins which don't have their latest version on npm :)

**Comment by knownasilya** [comment]
@kfatehi could you add me to npm for this plugin?

**Comment by kfatehi** [comment]
@knownasilya 

done, thank you

```
$ npm owner add knownasilya strider-ssh-deploy
+ knownasilya (strider-ssh-deploy)
```

**Comment by knownasilya** [comment]
Published. Thanks @kfatehi!

**Comment by mastertinner** [comment]
thanks a lot, guys!
