### ISSUE TITLE
Stream getting stuck pushing tarball with sftp writeStream

### ISSUE THREAD

**Issue by SamMorrowDrums** [Strider-CD/strider-ssh-deploy#38]
I've create an issue on the main SSH2 repo https://github.com/mscdex/ssh2/issues/421 and I was put on to using the fastPut method instead which seems to have worked for me!

Basically, the stream gets stuck, and eventually times out when I send my tarball, at 64kb every time. Something is going on with the buffer callbacks I'm pretty sure, but in the meantime it makes CI server hang for now reason. My solution for now is below:

```
conn.on('ready', function() {
        if (scp) {
          conn.sftp(function (err, sftp) {
            if (err) throw err;
            sftp.fastPut(scp.localBundlePath, paths.bundle, function() {
              runScript(conn, prepare(paths).concat(script), out, function(_exitCode) {
                exitCode = _exitCode;
              });
            })
          });
        } else {
          runScript(conn, script, out, function(_exitCode) {
            exitCode = _exitCode;
          });
        }
      })
```

Hopefully, we can use the stream eventually, but need to get to the bottom of why it is happening first!

**Comment by SamMorrowDrums** [comment]
It was Maximum Transfer Unit settings... Some weird setup on my server networking. `sudo ip link set eth0 mtu 1400` fixed the issue!

**Comment by knownasilya** [comment]
Nice!

**Comment by SamMorrowDrums** [comment]
Just in case anyone else ever encounters this:

The default on our cloud servers is an MTU of 64000 which has ben optimised by ProfitBricks for their internal networking. It fails on external ssh / scp commands!
